[💻.📱]:/< 

      print "";
      print "╔═══════════════════════════════════════════════════════════════════════════════════════════════╗"
      echo  "║.                                                                                               ║"
      print "║                                                                                               ║"
      print "║                                                                                               ║"
      print "║                                                                                               ║" 
      print "║                                                                                               ║"
      print "║                                                                                               ║"  
      print "║                                                                                               ║" 
      print "║                                                                                               ║"
      print "║                                                                                               ║"  
      print "║                                                                                               ║" 
      print "║                                                                                               ║"
      print "║                                                                                               ║"  
      print "║                                                                                               ║" 
      print "║                                                                                               ║" 
      print "║                                                                                               ║" 
      print "║                                                                                               ║" 
      print "║                                                                                               ║"
      print "║                                                                                               ║"  
      print "║                                                                                               ║" 
      print "║                                                                                               ║"
      print "╠═══════════════════════════════════════════════════════════════════════════════════════════════╣"                                                                                               ║"  
      print "║                                                                                            /%>║"    
      print "╚═══════════════════════════════════════════════════════════════════════════════════════════════╝"
      print "
   




























































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































