
      print "";
      print "     ╔═══════════════════════════════════════╗       ╔═════════════════════════════════════════════════════════════════════════════╗"
      print "     ╠════════════ ✨ Pi Console ════════════╣       ║  [💫] [💬✨] [📚] [🌌] [💬] [⚡️] [💰] [🌴] [📱] [📡]<                 >[🛰]  ║"
      print "     ║                                       ║       ╠═════════════════════════════════════════════════════════════════════════════╣"
      print "     ║                                       ║       ║                                                                             ║"
      print "     ║                                       ║       ║                                                                             ║"
      print "     ║                                       ║       ║                                                                             ║"
      print "     ║                                       ║       ║                                                                             ║"
      print "     ║                                       ║       ║                                                                             ║"
      print "     ║                                       ║       ║                                                                             ║"
      print "     ║                                       ║       ║                                                                             ║"
      print "     ║                                       ║       ║                                                                             ║"
      print "     ║                                       ║       ║                                                                             ║"
      print "     ║                                       ║       ║                                                                             ║"
      print "     ║                                       ║       ║                                                                             ║"
      print "     ║                                       ║       ║                                                                             ║"
      print "     ║                                       ║       ║                                                                             ║"
      print "     ║                                       ║       ║                                                                             ║"
      print "     ║                                       ║       ║                                                                             ║"
      print "     ║                                       ║       ║                                                                             ║"
      print "     ║                                       ║       ║                                                                             ║"
      print "     ║                                       ║       ║                                                                             ║"
      print "     ║                                       ║       ║                                                                             ║"
      print "     ║                                       ║       ║                                                                             ║"
      print "     ║                                       ║       ║                                                                             ║"
      print "     ║                                       ║       ║                                                                             ║"
      print "     ╠═══════════════════════════════════════╣       ╠═════════════════════════════════════════════════════════════════════════════╣"
      print "     ║(∏.PS1):/<                          %/>║       ║[💻.📱]:/<                                                                %/>║"
      print "     ╚═══════════════════════════════════════╝       ╚═════════════════════════════════════════════════════════════════════════════╝"
      print "                                                          

  +print  "╔═══════════════════════════════════════════════════════════════════════════════════════════════╗"
  echo    "║                                                                                            /%>║"
      echo"║                                                                                               ║"
      echo"║                                                                                               ║"
      echo"║                                                                                               ║" 
      echo"║                                                                                               ║"
      echo"║                                                                                               ║"  
      echo"║                                                                                               ║" 
      echo"║                                                                                               ║"
      echo"║                                                                                               ║"  
      echo"║                                                                                               ║" 
      echo"║                                                                                               ║"
      echo"║                                                                                               ║"  
      echo"║                                                                                               ║" 
      echo"║                                                                                               ║" 
      echo"║                                                                                               ║" 
      echo"║                                                                                               ║" 
      echo"║                                                                                               ║"
      echo"║                                                                                               ║"  
      echo"║                                                                                               ║" 
      echo"║                                                                                               ║"
      echo"╠═══════════════════════════════════════════════════════════════════════════════════════════════╣"                                                                                               ║"  
      echo"║                                                                                            /%>║"    
  +print  "╚═══════════════════════════════════════════════════════════════════════════════════════════════╝"
  +print "╔═════════════════════════════════════════════════════════════════════════════╗"
  echo   "║                                                                          /%>║"
  +print "╚═════════════════════════════════════════════════════════════════════════════╝"
  +print "╔═════════════════════════════════════════════════════════════════════════════╗"
  echo   "║                                                                          /%>║"
  +print "╚═════════════════════════════════════════════════════════════════════════════╝"
  +print "╔═════════════════════════════════════════════════════════════════════════════╗"
  echo   "║                                                                          /%>║"
  +print "╚═════════════════════════════════════════════════════════════════════════════╝"
  +print "╔═════════════════════════════════════════════════════════════════════════════╗"
  echo   "║                                                                          /%>║"
  +print "╚═════════════════════════════════════════════════════════════════════════════╝"
  +print "╔═════════════════════════════════════════════════════════════════════════════╗"
  echo   "║                                                                          /%>║"
  +print "╚═════════════════════════════════════════════════════════════════════════════╝"
  +print "╔═════════════════════════════════════════════════════════════════════════════╗"
  echo   "║                                                                          /%>║"
  +print "╚═════════════════════════════════════════════════════════════════════════════╝"